version: '3'
services:
  wordpress:
     build: ./requirements/wordpress
     image: wordpress
     container_name: wordpress
     restart: unless-stopped
     ports:
         - "9000"
     env_file:
      - .env
     volumes:
         - ./requirements/wordpress/files:/var/www/html
     networks:
      - network
  nginx:
     build: ./requirements/nginx
     image: nginx
     container_name: nginx
     restart: unless-stopped
     volumes:
      - ./requirements/wordpress/files:/var/www/html
     ports:
       - "443:443"
     networks:
      - network
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb/
      args:
       - DB_USER=$DB_USER
       - DB_PASSWORD=$DB_PASSWORD
       - DB_NAME=$DB_NAME
    restart: unless-stopped
    volumes:
       - ./data:/koko
    container_name: "mariadb"
    ports:
      - "3306"
    networks:
      - network
networks:
   network:
